version: "3"

services:
  dev:
    container_name: chat-dev-hot
    image: chat-dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev:hot
volumes:
  node_modules:
